### ISSUE TITLE
Compatibility with elm-css v17 and higher

### ISSUE THREAD

**Issue by nitramburesh** [perzanko/elm-loading#6]
Hi!
Since the package `elm-css` has recently been bumped to version 17 bringing new features and optimizations, we wanted to upgrade the package in our project. However we found ourselves using this `elm-loading` package which is not compatible with higher versions of `elm-css`. In the past we've had very convenient experience with this package and would love to carry on using it. 

Are you planning on updating the package and supporting the newer versions of `elm-css`? :)

**Comment by perzanko** [comment]
Thanks @nitramburesh for reporting and thanks @darkensk for your commit!:) 

Merged and released in version 2.0.5
